spring.application.name=appiumTest

appium.device.name=iPhone 17 Pro
appium.udid.id=18E7B83D-DB6F-4728-89BE-A2990EB2E06C
appium.device.version=26.5
appium.platform.run=IOS
#appium.platform.name=Android
#appium.device.name=AshishPixel5
#appium.udid.id=emulator-5554
appium.platform.name=